### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wmf-maho** [svenlr/car-physics-pacejka#1]
[ 16%] Generating /home/code/car-physics-pacejka/generated/libacados_sim_solver_car.so
Traceback (most recent call last):
  File "car_sim_gen/generate_car_sim.py", line 9, in <module>
    from car_sim_gen.car_model import create_car_model
  File "/home/code/car-physics-pacejka/car_sim_gen/car_model.py", line 4, in <module>
    from acados_template.acados_ocp_formulation_helper import get_symbol, auto_xdot
ModuleNotFoundError: No module named 'acados_template.acados_ocp_formulation_helper'
make[2]: *** [/home/code/car-physics-pacejka/generated/libacados_sim_solver_car.so] Error 1
make[1]: *** [CMakeFiles/acados_sim_solver_car_generate.dir/all] Error 2
make: *** [all] Error 2

when I try build, it's error
I can't find "acados_ocp_formulation_helper" file in acados_template

**Comment by svenlr** [comment]
Hi, try using this fork of acados instead:
https://github.com/svenlr/acados
